POST http://127.0.0.1:8000/customer/register HTTP/1.1
content-type: application/json

{
    "first_name": "Faizan",
    "last_name": "Bardai",
    "address": "abc112",
    "phone": "112",
    "email": "faizan@bardai.com",
    "password": "hello123@"
}

###

POST http://127.0.0.1:8000/customer/login HTTP/1.1
content-type: application/json

{
    "email": "faizan@bardai.com",
    "password": "hello123@"
}

###

GET http://127.0.0.1:8000/customer/data HTTP/1.1
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaXJzdE5hbWUiOiJGYWl6YW4iLCJsYXN0TmFtZSI6IkJhcmRhaSIsImFkZHJlc3MiOiJhYmMxMTIiLCJwaG9uZSI6IjExMiIsImVtYWlsIjoiZmFpemFuQGJhcmRhaS5jb20iLCJleHAiOjE2NTM4Njc4MDh9.b75RlY1Td33IpYH6G6iZIp2vDn_8UZcwTM665y56Fw0

###

POST http://127.0.0.1:8000/customer/create-bank-account HTTP/1.1
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaXJzdE5hbWUiOiJGYWl6YW4iLCJsYXN0TmFtZSI6IkJhcmRhaSIsImFkZHJlc3MiOiJhYmMxMTIiLCJwaG9uZSI6IjExMiIsImVtYWlsIjoiZmFpemFuQGJhcmRhaS5jb20iLCJleHAiOjE2NTM4Njc4MDh9.b75RlY1Td33IpYH6G6iZIp2vDn_8UZcwTM665y56Fw0
content-type: application/json

{
    "type": "current",
    "name": "ABC"
}

###

GET http://127.0.0.1:8000/customer/bank-accounts HTTP/1.1
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaXJzdE5hbWUiOiJGYWl6YW4iLCJsYXN0TmFtZSI6IkJhcmRhaSIsImFkZHJlc3MiOiJhYmMxMTIiLCJwaG9uZSI6IjExMiIsImVtYWlsIjoiZmFpemFuQGJhcmRhaS5jb20iLCJleHAiOjE2NTM4Njc4MDh9.b75RlY1Td33IpYH6G6iZIp2vDn_8UZcwTM665y56Fw0

###

POST http://127.0.0.1:8000/customer/deposit HTTP/1.1
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaXJzdE5hbWUiOiJGYWl6YW4iLCJsYXN0TmFtZSI6IkJhcmRhaSIsImFkZHJlc3MiOiJhYmMxMTIiLCJwaG9uZSI6IjExMiIsImVtYWlsIjoiZmFpemFuQGJhcmRhaS5jb20iLCJleHAiOjE2NTM4Njc4MDh9.b75RlY1Td33IpYH6G6iZIp2vDn_8UZcwTM665y56Fw0
content-type: application/json

{
    "type": "current",
    "number": "470fbca0-70c5-4066-9845-905170a09eaf",
    "amount": "100.50"
}

###

POST http://127.0.0.1:8000/customer/withdraw HTTP/1.1
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmaXJzdE5hbWUiOiJGYWl6YW4iLCJsYXN0TmFtZSI6IkJhcmRhaSIsImFkZHJlc3MiOiJhYmMxMTIiLCJwaG9uZSI6IjExMiIsImVtYWlsIjoiZmFpemFuQGJhcmRhaS5jb20iLCJleHAiOjE2NTM4Njc4MDh9.b75RlY1Td33IpYH6G6iZIp2vDn_8UZcwTM665y56Fw0
content-type: application/json

{
    "type": "current",
    "number": "470fbca0-70c5-4066-9845-905170a09eaf",
    "amount": "200.50"
}

###


POST http://127.0.0.1:8000/admin/login HTTP/1.1
content-type: application/json

{
    "email": "admin@redi-school.com",
    "password": "admin123@"
}

###

GET http://127.0.0.1:8000/admin/customers HTTP/1.1
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQHJlZGktc2Nob29sLmNvbSIsImV4cCI6MTY1NDM0NjYxMn0.-uZfRCXDcNxLgupBVcmYWbpxZB4gLVA73Z_H2QvqSdA
